name: Python application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  lint-with-flake8:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pyinstaller
          pip install -r requerements.txt
      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile setup.py
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: executable
          path: dist/setup.exe # Sesuaikan dengan hasil build PyInstaller
