name: Build Executable with PyInstaller

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest  # Bisa diganti dengan windows-latest atau macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Ganti versi Python sesuai kebutuhan

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirement.txt
          pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile setup.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: executable
          path: dist/main  # Sesuaikan dengan hasil build PyInstaller
